app_spot_index:
    path: /spots
    methods: [GET]
    defaults:
        _controller: app.controller.spot:indexAction
        _sylius:
            template: :Spot:index.html.twig
            repository:
                method: createEnabledPaginator

app_spot_index_by_spotter:
    path: /my-spots
    methods: [GET]
    defaults:
        _controller: app.controller.spot:indexAction
        _sylius:
            template: :Spot:index.html.twig
            repository:
                method: createEnabledBySpotterPaginator
                arguments: ["expr:service('security.context').getToken().getUser()"]

app_spot_show:
    path: /spots/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.spot:showAction
        _sylius:
            template: :Spot:show.html.twig
