app_spot_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.spot:indexAction
        _sylius:
            template: :Spot:index.html.twig
            repository:
                method: createEnabledPaginator

app_spot_index_by_spotter:
    path: /my
    methods: [GET]
    defaults:
        _controller: app.controller.spot:indexAction
        _sylius:
            template: :Spot:index.html.twig
            repository:
                method: createEnabledBySpotterPaginator
                arguments: ["expr:service('security.context').getToken().getUser()"]

app_spot_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.spot:createAction
        _sylius:
            template: :Spot:create.html.twig
            redirect: app_spot_index
            flash: app.spot.added

app_spot_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: app.controller.spot:showAction
        _sylius:
            template: :Spot:show.html.twig
