sylius_resource:
    resources:
        app.make:
            classes:
                model: AppBundle\Entity\Make
                form:
                    default: AppBundle\Form\Type\MakeType
        app.model:
            classes:
                model: AppBundle\Entity\Model
                form:
                    default: AppBundle\Form\Type\ModelType
        app.photo:
            classes:
                model: AppBundle\Entity\Photo
                form:
                    default: AppBundle\Form\Type\PhotoType
        app.spot:
            classes:
                model: AppBundle\Entity\Spot
                repository: AppBundle\Doctrine\ORM\SpotRepository
        app.spotter:
            classes:
                model: AppBundle\Entity\Spotter
