sylius_resource:
    resources:
        app.make:
            classes:
                model: AppBundle\Entity\Make
        app.model:
            classes:
                model: AppBundle\Entity\Model
                form:
                    default: AppBundle\Form\Type\ModelType
        app.spot:
            classes:
                model: AppBundle\Entity\Spot
                repository: AppBundle\Doctrine\ORM\SpotRepository
                form:
                    default: AppBundle\Form\Type\SpotType
        app.spotter:
            classes:
                model: AppBundle\Entity\Spotter
