sylius_resource:
    resources:
        app.make:
            classes:
                model: AppBundle\Entity\Make
        app.model:
            classes:
                model: AppBundle\Entity\Model
