app_ui:
    resource: "routing/ui.yml"

app_admin:
    resource: "routing/admin.yml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
