default:
    suites:
        admin_managing_makes:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.make
                - app.behat.context.setup.security

                - app.behat.context.transform.shared_storage

                - app.behat.context.admin.managing_makes
                - app.behat.context.admin.notification
            filters:
                tags: "@managing_makes && @ui"
