default:
    suites:
        admin_managing_models:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.make
                - app.behat.context.setup.model
                - app.behat.context.setup.security

                - app.behat.context.transform.model
                - app.behat.context.transform.shared_storage

                - app.behat.context.admin.managing_models
                - app.behat.context.admin.notification
            filters:
                tags: "@managing_models && @ui"
