default:
    suites:
        admin_managing_spotters:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.security
                - app.behat.context.setup.spotter

                - app.behat.context.transform.shared_storage
                - app.behat.context.transform.spotter

                - app.behat.context.admin.managing_spotters
                - app.behat.context.admin.notification
            filters:
                tags: "@managing_spotters && @ui"
