AppBundle\Entity\Make:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: app.make.name.unique
    properties:
        name:
            - NotBlank:
                message: app.make.name.not_blank

AppBundle\Entity\Model:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [make, name]
            message: app.model.name.unique
    properties:
        name:
            - NotBlank:
                message: app.model.name.not_blank
        make:
            - NotBlank:
                message: app.model.make.not_blank
