default:
    suites:
        ui_homepage:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.ui.home
            filters:
                tags: "@homepage && @ui"
