default:
    suites:
        ui_registering:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.spotter

                - app.behat.context.transform.shared_storage

                - app.behat.context.ui.home
                - app.behat.context.ui.register
            filters:
                tags: "@registering && @ui"
