default:
    suites:
        ui_signing_in:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.spotter

                - app.behat.context.transform.shared_storage

                - app.behat.context.ui.home
                - app.behat.context.ui.login
            filters:
                tags: "@signing_in && @ui"
