default:
    suites:
        ui_spot:
            contexts_as_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.model
                - app.behat.context.setup.spot
                - app.behat.context.setup.spotter

                - app.behat.context.transform.make
                - app.behat.context.transform.model
                - app.behat.context.transform.shared_storage

                - app.behat.context.ui.spot
            filters:
                tags: "@spot && @ui"
