AppBundle\Entity\Make:
    type: entity
    table: make
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        path:
            type: string
            nullable: true
    oneToMany:
        models:
            targetEntity: AppBundle\Entity\Model
            mappedBy: make
            cascade: ["persist", "remove"]
