AppBundle\Entity\Spotter:
    type: entity
    table: spotter
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    attributeOverride:
        salt:
            column: salt
            type: string
            nullable: true
    oneToMany:
        spots:
            targetEntity: AppBundle\Entity\Spot
            mappedBy: spotter
            cascade: ["persist", "remove"]
