AppBundle\Entity\Spot:
    type: entity
    table: spot
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        description:
            type: string
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        lat:
            type: float
            nullable: true
        lng:
            type: float
            nullable: true
        country:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        illegiblePlate:
            column: illegible_plate
            type: boolean
        licensePlate:
            column: license_plate
            type: string
            nullable: true
        enabled:
            column: enabled
            type: boolean
    manyToOne:
        make:
            targetEntity: AppBundle\Entity\Make
            joinColumn:
                name: make_id
                referencedColumnName: id
                onDelete: "CASCADE"
        model:
            targetEntity: AppBundle\Entity\Model
            joinColumn:
                name: model_id
                referencedColumnName: id
                onDelete: "CASCADE"
        spotter:
            targetEntity: AppBundle\Entity\Spotter
            inversedBy: spots
            joinColumn:
                name: spotter_id
                referencedColumnName: id
                onDelete: "CASCADE"
    oneToMany:
        photos:
            targetEntity: AppBundle\Entity\Photo
            mappedBy: spot
            cascade: ["all"]
