app_admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true

app_admin_dashboard:
    path: /admin/dashboard
    defaults:
        _controller: app.controller.homepage:indexAction
        template: :Admin/Dashboard:index.html.twig

app_admin_make:
    resource: "admin/make.yml"
    prefix: /admin
