sylius_grid:
    grids:
        app_admin_make:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Make
            sorting:
                name: asc
            fields:
                id:
                    type: string
                    label: app.id
                logo:
                    type: twig
                    label: app.logo
                    path: .
                    options:
                        template: :Admin/Make/Field:logo.html.twig
                name:
                    type: string
                    label: app.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
