sylius_grid:
    grids:
        app_admin_model:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Model
            sorting:
                name: asc
            fields:
                id:
                    type: string
                    label: app.id
                make:
                    type: twig
                    label: app.make
                    options:
                        template: :Grid/Field:make.html.twig
                name:
                    type: string
                    label: app.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
